# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fa444a54276097f398875fab7dde26800ae74881eacb5d9ce820aaf8830bf7eb8ee6053ba686f47096d7c075097e70c197fa82d837c7a3533e786babe4891b1

test:
  secret_key_base: a6794595f46d0a598db5257aa0cb8b415a24fa44ca72af6645b28985442f1a0080fc512b63abd6cc1a87576f28f079d567ccd7253870cc46ea0a70d36c438a1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
